version: '3'
services:
  next-app:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./:/app
  nginx:
    build: ./nginx/
    ports:
      - 80:80
  predict:
    build: ./prediction
    ports:
      - 8080:8080